name: "Deploy"

on:
  workflow_dispatch:

env:
  working-directory: .
  resource-group: rg-devops-student-tom
  app-service-name: tom-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      - name: Install dependencies
        run: dotnet restore
        working-directory: ${{ env.working-directory }}
      - name: Build
        run: dotnet build --configuration Release
        working-directory: ${{ env.working-directory }}
      - name: Publish
        run: dotnet publish --configuration Release --output ./publish
        working-directory: ${{ env.working-directory }}
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: webapi
          path: ${{ env.working-directory }}/publish
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapi

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.app-service-name }}
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
          package: .
          slot-name: production